export const testimonials = [
    {
      logoImage:"https://cdn.marvel.com/content/1x/echo_lob_log_eye_01_0.png",
      sub:`STREAM THE 5-EPISODE EVENT NOW!`,
      sub2:'THE ROXXON AGE OF MARVEL COMICS BEGINS',
      image: "https://cdn.marvel.com/content/1x/echo_0109_com_mas_dsk_01.jpg",
      image2: "https://cdn.marvel.com/u/prod/marvel/i/mg/b/d0/65b2b4bc56bd1.jpg",
      title: "Echo now Streaming",
      btn1:"Read More",
      btn3:"READ NOW",
      link1: "https://www.daum.net",
    },
    {
      logoImage:"https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Marvel_Studios_2016_logo.svg/2560px-Marvel_Studios_2016_logo.svg.png",
      size:"w-[300px] h-[75px]",
      image: "https://cdn.marvel.com/content/1x/voices_0129_com_mas_dsk_01.jpg",
      image2: "https://cdn.marvel.com/content/1x/voices_0129_com_mas_dsk_01.jpg",
      sub:`this week's new comics`,
      sub2:" Captain America graces the city skies - and dives headlong into the dangers of its alleyways.'",
      article:`Meet the Dead X-Men, behold Sabretooth's big plans for Wolverine, join Shang-Chi's fight for Chinatown, and more in this week's comics!`,
      title: "The Week's New Comics",
      btn1:"Read More",
      btn3:"READ NOW",
      link1: "https://www.daum.net"
    },
    {
      logoImage:"https://cdn.marvel.com/content/1x/whatifs2_log_eye_02.png",
      image: "https://cdn.marvel.com/content/1x/watchers9days_com_mas_dsk_01.jpg",
      image2: "https://cdn.marvel.com/u/prod/marvel/i/mg/c/d0/65b3ed2b78b9e.jpg",
      article:`Check back each day at 9am PST for new reveals and exclusive gifts as we watch Season 2 of Marvel Studio's What If...? Now streaming on Disney+.`,
      sub:`the watcher's nine days of what if...?`,
      sub2:"YOUR COMPLETE GUIDE TO 'WOMEN OF MARVEL'",
      title: "What if.. Season..2",
      btn1:"Read More",
      link1: "https://www.daum.net",
      btn2:"Stream On Hold",
      btn3:"READ NOW",
      link2: "https://www.daum.net"
    },
    {
      logoImage:"https://cdn.marvel.com/content/1x/mulogo_lob_log_eye_01_1.png",
      image: "https://cdn.marvel.com/content/1x/echo_mu_com_mas_dsk_01.jpg",
      image2: "https://cdn.marvel.com/u/prod/marvel/i/mg/5/f0/65642c5403bdb.jpg",
      article:`Read our Echo comic picks on Marvel Unlimited ahead of the series premiere on January 10!`,
      sub:`echo comics to read`,
      sub2:'MEET GENIS-VELL, THE SON OF THE FIRST CAPTAIN MARVEL',
      title: "Echo Comics To Read",
      btn1:"Read More",
      btn3:"READ NOW",
      link1: "https://www.daum.net"
    },
    {
      logoImage:"https://cdn.marvel.com/content/1x/marvelsblade_lob_log_eye_01.png",
      image: "https://cdn.marvel.com/content/1x/marvelsblade_lob_mas_dsk_01.jpg",
      image2: "https://cdn.marvel.com/u/prod/marvel/i/mg/3/c0/65642dd1527d9.jpg",
      article:`Watch the Game Awards 2023 trailer for 'Marvel's Blade' now!`,
      sub:`announcement trailer`,
      sub2:"MEET ANTI-VENOM, THE VENOM SYMBIOTE'S POLAR OPPOSITE",
      title: "Marvel's Blade' In Development",
      btn1:"Read More",
      btn3:"READ NOW",
      link1: "https://www.daum.net"
    },
  ]